/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_Account */

#ifndef _Included_com_jni_Account
#define _Included_com_jni_Account

#include <Android/log.h>

#define LOG(...) __android_log_print(ANDROID_LOG_ERROR,"Native",__VA_ARGS__)

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_Account
 * Method:    statistic
 * Signature: (Lcom/jni/ActInfo;)V
 */

JNIEXPORT void JNICALL Java_com_jni_Account_statistic
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_jni_Account
 * Method:    isVerfyPoint
 * Signature: (Lcom/jni/BtPoint;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_Account_isVerfyPoint
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
