package com.alex.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.alex.greendao.WorkPoint;
import com.alex.greendao.TrackInfo;

import com.alex.greendao.WorkPointDao;
import com.alex.greendao.TrackInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig workPointDaoConfig;
    private final DaoConfig trackInfoDaoConfig;

    private final WorkPointDao workPointDao;
    private final TrackInfoDao trackInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        workPointDaoConfig = daoConfigMap.get(WorkPointDao.class).clone();
        workPointDaoConfig.initIdentityScope(type);

        trackInfoDaoConfig = daoConfigMap.get(TrackInfoDao.class).clone();
        trackInfoDaoConfig.initIdentityScope(type);

        workPointDao = new WorkPointDao(workPointDaoConfig, this);
        trackInfoDao = new TrackInfoDao(trackInfoDaoConfig, this);

        registerDao(WorkPoint.class, workPointDao);
        registerDao(TrackInfo.class, trackInfoDao);
    }
    
    public void clear() {
        workPointDaoConfig.getIdentityScope().clear();
        trackInfoDaoConfig.getIdentityScope().clear();
    }

    public WorkPointDao getWorkPointDao() {
        return workPointDao;
    }

    public TrackInfoDao getTrackInfoDao() {
        return trackInfoDao;
    }

}
